apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config-map
data:
  ACTIVE_PROFILE: production
  KAFKA_SERVER: kafka-service
  KAFKA_ADVERTISED_HOST_NAME: kafka-service
  KAFKA_ZOOKEEPER_CONNECT: zookeeper-service
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: training
