apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - image: landrzejewski/products
          name: products
          envFrom:
            - configMapRef:
                name: products-config-map
          ports:
            - containerPort: 9001
              name: http
