apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-1
  labels:
    share: volume-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/volume-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-2
  labels:
    share: volume-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/volume-2