apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-server-repica-set
spec:
  replicas: 5
  selector:
    matchLabels:
      app-name: web-server
  template:
    metadata:
      labels:
        app-name: web-server
    spec:
      containers:
        - name: web-server
          image: nginx:1.17.3-alpine
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  ports:
    - port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /echo
            backend:
              serviceName: echo-server-service
              servicePort: 80
          - path: /web(/|$)(.*)
            backend:
              serviceName: web-server-service
              servicePort: 80









